// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nudsvpkobrqpnpdutnsu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im51ZHN2cGtvYnJxcG5wZHV0bnN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4NzkzMTEsImV4cCI6MjA2NTQ1NTMxMX0.JdWCS3KKAu3QifP3yke1dWBMmt65tKzPh7ZzyH7SrmA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);